### PR TITLE
Add support for _block_invoke in c++ and objc

### PR DESCRIPTION
**Pull request by wargio**
# SQUASH ME

Describes function blocks that don't have a name specified in source code.
Ex: _ZN1Parent_Funciton_block_invoke_1

https://reviews.llvm.org/D74813

### CODE REVIEW

**Comment by XVilka** [comment]
Many these warnings:
```
../subprojects/libdemangle/src/demangler_util.c: assertion 'ds && string' failed (line 169)
```

**Comment by XVilka** [comment]
@wargio it solved the original problem, thanks!

**Comment by wargio** [comment]
they are indeed not demangled. could you provide the original strings?

**Comment by XVilka** [comment]
@wargio not sure if these are originals (got them with `rizin -e bin.demangle=false`:
```
[0x100006060]> is~XPCAgent~__
89   0x0004caf8 0x100008af8 LOCAL  FUNC 0        ___32+[XPCAgentServer sharedInstance]_block_invoke
91   0x0004ccbc 0x100008cbc LOCAL  FUNC 0        ___53-[XPCAgentServer listener:shouldAcceptNewConnection:]_block_invoke
92   0x0004cd28 0x100008d28 LOCAL  FUNC 0        ___53-[XPCAgentServer listener:shouldAcceptNewConnection:]_block_invoke.46
97   0x0004d46c 0x10000946c LOCAL  FUNC 0        ___55-[XPCAgentServer notifyUser:noticeId:notificationType:]_block_invoke
102  0x0004e058 0x10000a058 LOCAL  FUNC 0        ___59-[XPCAgentServer activateUniversalAccessAuthWarn:interval:]_block_invoke
104  0x0004e2bc 0x10000a2bc LOCAL  FUNC 0        ___27-[XPCAgentServer launchApp]_block_invoke
105  0x0004e3d4 0x10000a3d4 LOCAL  FUNC 0        ___27-[XPCAgentServer launchApp]_block_invoke.118
109  0x0004e898 0x10000a898 LOCAL  FUNC 0        ___25-[XPCAgentServer restart]_block_invoke
260  0x000565e8 0x1000125e8 LOCAL  FUNC 0        __OBJC_$_CLASS_METHODS_XPCAgentServer
261  0x00056600 0x100012600 LOCAL  FUNC 0        __OBJC_$_INSTANCE_METHODS_XPCAgentServer
426  0x00060d18 0x10001cd18 LOCAL  FUNC 0        __OBJC_CLASS_PROTOCOLS_$_XPCAgentServer
427  0x00060d30 0x10001cd30 LOCAL  FUNC 0        __OBJC_METACLASS_RO_$_XPCAgentServer
428  0x00060d78 0x10001cd78 LOCAL  FUNC 0        __OBJC_$_INSTANCE_VARIABLES_XPCAgentServer
429  0x00060dc0 0x10001cdc0 LOCAL  FUNC 0        __OBJC_$_PROP_LIST_XPCAgentServer
430  0x00060e28 0x10001ce28 LOCAL  FUNC 0        __OBJC_CLASS_RO_$_XPCAgentServer
```

**Comment by wargio** [comment]
@XVilka can you try again?

**Review by XVilka — APPROVED** [review]
Much better now. Only left strings are:
```
[0x100006060]> afl~sym.___
0x1000053c0    1 52           sym.___copy_helper_block_ea8_32s40r
0x1000053f4    1 44           sym.___destroy_helper_block_ea8_32s40r
0x100005b30    1 8            sym.___copy_helper_block_ea8_32s
0x100005b38    1 8            sym.___destroy_helper_block_ea8_32s
0x10000616c    1 72           sym.___main_block_invoke
0x100008364    1 12           sym.___clang_call_terminate
0x10000d0e0    1 48           sym.___copy_helper_block_ea8_32s40s48s
0x10000d110    1 48           sym.___destroy_helper_block_ea8_32s40s48s
0x10000d230    1 40           sym.___copy_helper_block_ea8_32s40s
0x10000d258    1 40           sym.___destroy_helper_block_ea8_32s40s
0x100010de4   10 196          sym.___isOSVersionAtLeast
0x100010eb0   18 332          sym.___isPlatformVersionAtLeast
0x100011004   28 512          sym.___isPlatformOrVariantPlatformVersionAtLeast
0x100011534    1 36           sym.___isPlatformOrVariantPlatformVersionAtLeast.cold.1
```

**Comment by wargio** [comment]
Nice!

**Pull request merged**
